
title: "Nue: The closer-to-standards web framework"
desc: Simple Next.js and Astro alternative with universal hot-reloading, hybrid client-side routing, extremely fast build times, and more.
logo: /img/logo.png
favicon: /global/logo/stack.svg
og: /img/og.jpg
baseurl: https://nuejs.org
theme-color: #00C2FF

# Design assets
icons: /global/icons
site-top: false

mastnav:
  - FAQ
  - Docs
  - Blog

banner:
  label: Nuemark is here!
  url: /blog/introducing-nuemark/

footnav:
  - FAQ
  - Docs
  - Blog
  - label: Backstory
    url: /blog/backstory/
  - img: /global/icons/github.svg
    url: https://github.com/nuejs/nue
    class: octocat

subnav:
  - img: /global/icons/github.svg
    url: https://github.com/nuejs/nue
    class: octocat
  - img: /global/icons/menu.svg
    hash: mobile-nav
    class: burger

  # - label: Poll
  #   class: small secondary poll
  #   role: button


# port: 5000
hotreload: true
# use_router: true

# generation
globals: [global, style, lib]
secondary_css: [css2, secondary, 2.]
inline_css: true

preview:
  ssl_key: .ssl/localhost+1-key.pem
  ssl_cert: .ssl/localhost+1.pem