
title: Nue / Frontend troublesolver
desc: A powerful React/Vue/Vite/Astro alternative
logo: /global/logo/logo.png
favicon: /global/logo/stack.svg
og: /global/img/og.jpg
baseurl: https://nuejs.org
theme-color: #00C2FF

# Design assets
icons: /global/icons
site-top: false

mastnav:
  - Why
  - Backstory
  - Tools
  - label: Docs
    url: /docs/nuejs/
  - FAQ

footnav:
  - Why
  - Backstory
  - Tools
  - label: Docs
    url: /docs/nuejs/
  - FAQ
  - label: Compare
    url: /compare/component.html
  - img: /global/icons/github.svg
    url: https://github.com/nuejs/nuejs
    class: octocat

subnav:
  - img: /global/icons/github.svg
    url: https://github.com/nuejs/nuejs
    class: octocat
  - img: /global/icons/menu.svg
    hash: mobile-nav
    class: burger

  # - label: Poll
  #   class: small secondary poll
  #   role: button


# port: 5000
hotreload: true
# use_router: true

# generation
globals: [global, style, lib]
secondary_css: [css2, secondary, 2.]
inline_css: true

preview:
  ssl_key: .ssl/localhost+1-key.pem
  ssl_cert: .ssl/localhost+1.pem